---
abstract: 'the distribution metadata for a CPAN dist'
author:
  - 'David Golden <dagolden@cpan.org>'
  - 'Ricardo Signes <rjbs@cpan.org>'
build_requires:
  Data::Dumper: 0
  File::Spec: 0
  File::Temp: 0.20
  IO::Dir: 0
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 3.101421, CPAN::Meta::Converter version 2.101450'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CPAN-Meta
no_index:
  directory:
    - history
requires:
  Carp: 0
  JSON: 2
  Parse::CPAN::Meta: 0
  Scalar::Util: 0
  Storable: 0
  Version::Requirements: 0.101020
  autodie: 0
  perl: 5.006
resources:
  repository: http://github.com/dagolden/cpan-meta.git
version: 2.101460
x_Dist_Zilla:
  plugins:
    -
      class: Dist::Zilla::Plugin::MetaNoIndex
      name: MetaNoIndex
      version: 1.101200
    -
      class: Dist::Zilla::Plugin::CheckExtraTests
      name: CheckExtraTests
      version: 0.004
    -
      class: Dist::Zilla::Plugin::CheckChangesHasContent
      name: CheckChangesHasContent
      version: 0.002
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@Filter/@Basic/GatherDir'
      version: 3.101421
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@Filter/@Basic/PruneCruft'
      version: 3.101421
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@Filter/@Basic/ManifestSkip'
      version: 3.101421
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@Filter/@Basic/MetaYAML'
      version: 3.101421
    -
      class: Dist::Zilla::Plugin::License
      name: '@Filter/@Basic/License'
      version: 3.101421
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@Filter/@Basic/Readme'
      version: 3.101421
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@Filter/@Basic/ExecDir'
      version: 3.101421
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@Filter/@Basic/ShareDir'
      version: 3.101421
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: '@Filter/@Basic/MakeMaker'
      version: 3.101421
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@Filter/@Basic/Manifest'
      version: 3.101421
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@Filter/@Basic/TestRelease'
      version: 3.101421
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@Filter/@Basic/ConfirmRelease'
      version: 3.101421
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@Filter/@Basic/UploadToCPAN'
      version: 3.101421
    -
      class: Dist::Zilla::Plugin::AutoPrereq
      name: '@Filter/AutoPrereq'
      version: 3.101421
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@Filter/PkgVersion'
      version: 3.101421
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@Filter/MetaConfig'
      version: 3.101421
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@Filter/MetaJSON'
      version: 3.101421
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@Filter/NextRelease'
      version: 3.101421
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@Filter/PodSyntaxTests'
      version: 3.101421
    -
      class: Dist::Zilla::Plugin::Repository
      name: '@Filter/Repository'
      version: 0.12
    -
      class: Dist::Zilla::Plugin::PodWeaver
      name: '@Filter/PodWeaver'
      version: 3.100710
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@Filter/@Git/Check'
      version: 1.101230
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@Filter/@Git/Commit'
      version: 1.101230
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@Filter/@Git/Tag'
      version: 1.101230
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: '@Filter/@Git/Push'
      version: 1.101230
    -
      class: Dist::Zilla::Plugin::AutoVersion
      name: AutoVersion
      version: 3.101421
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: Git::Push
      version: 1.101230
    -
      class: Dist::Zilla::Plugin::MetaResources
      name: MetaResources
      version: 3.101421
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 3.101421
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 3.101421
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 3.101421
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 3.101421
  zilla:
    class: Dist::Zilla
    config:
      is_trial: 0
    version: 3.101421
