use strict;
use warnings;
use Test::More;

# generated by Dist::Zilla::Plugin::Test::PodSpelling 2.004003
eval "use Test::Spelling 0.12; use Pod::Wordlist::hanekomu; 1" or die $@;


add_stopwords(<DATA>);
all_pod_files_spelling_ok( qw( bin lib  ) );
__DATA__
Ansgar
Arnfjörð
Baz
Bjarmason
Burchardt
CPANPLUS
CamelCase
Damyan
Gregor
Hermann
IETF
IMPLEMENTORS
Ivanov
JSON
Locator
Madsen
Prereq
Prereqs
SIGNES
Timmermans
URL's
UTF
arrayrefs
bzr
cvs
darcs
deserialized
deserializes
dir
distmeta
hashrefs
hg
installable
invocant
json
lossy
mailto
parsers
pathname
prereq
prereqs
runtime
shortplanks
subkey
subkeys
subtype
subtypes
svn
unix
unordered
url
Ævar
David
Golden
dagolden
Ricardo
Signes
rjbs
and
lib
CPAN
Meta
History
Validator
Converter
Feature
Spec
