use strict;
use warnings;
use Test::More;

# generated by Dist::Zilla::Plugin::Test::PodSpelling 2.006000
eval "use Test::Spelling 0.12; use Pod::Wordlist::hanekomu; 1" or die $@;


add_stopwords(<DATA>);
all_pod_files_spelling_ok( qw( bin lib  ) );
__DATA__
IMPLEMENTORS
URL's
arrayrefs
deserializes
dir
distmeta
hashrefs
installable
json
lossy
parsers
pathname
subkey
subkeys
subtype
subtypes
unix
unordered
David
Golden
dagolden
Ricardo
Signes
rjbs
and
Ansgar
Burchardt
ansgar
Avar
Arnfjord
Bjarmason
avar
Christopher
Madsen
cjm
Cory
Watson
gphat
Damyan
Ivanov
dam
Eric
Wilhelm
ewilhelm
Gregor
Hermann
gregoa
Karen
Etheridge
ether
Ken
Williams
kwilliams
Kenichi
Ishigaki
ishigaki
Lars
Dieckow
daxim
Leon
Timmermans
leont
Mark
Fowler
markf
Michael
Schwern
mschwern
Olaf
Alders
olaf
Olivier
Mengué
dolmen
Randy
Sims
randys
lib
CPAN
Meta
Prereqs
History
Spec
Converter
Validator
Feature
